# Copyright (C) 2026 - 2026, Ota. All Rights Reserved.
# Licensed under the Apache License, Version 2.0. See LICENSE for the full license text.

name: Ota governance

on:
  push:
    branches:
      - bobai/athena-api-ota-readiness
  pull_request:
    paths:
      - ota.yaml
      - .github/workflows/ota-governance.yml
      - .github/workflows/ota-verify-static-native-linux.yml
      - .github/workflows/ota-verify-static-container-linux.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify-static-native-linux:
    uses: ./.github/workflows/ota-verify-static-native-linux.yml
    with:
      ota_projection_identity: sha256:5c83ae6f8b86ea06f28ecb31525cbc48105b307529d6a34b1f955d01dd0102f9
      ota_target_os: linux
      ota_runner: ubuntu-latest

  verify-static-container-linux:
    uses: ./.github/workflows/ota-verify-static-container-linux.yml
    with:
      ota_projection_identity: sha256:f81b158f7efad00a362b6ddc566521df222e1deb72273792293e7e81cf063466
      ota_target_os: linux
      ota_runner: ubuntu-latest
